### ISSUE TITLE
Can't Build

### ISSUE THREAD

**Issue by goodZhaoliu** [umbrella22/electron-vue-template#18]
• packaging       platform=win32 arch=x64 electron=7.3.0 appOutDir=build\win-unpacked
  ⨯ Get "=7.3.0/electron-v7.3.0-win32-x64.zip": unsupported protocol scheme ""
github.com/develar/app-builder/pkg/download.(*Downloader).follow.func1
        /Volumes/data/Documents/app-builder/pkg/download/downloader.go:192
github.com/develar/app-builder/pkg/download.(*Downloader).follow
        /Volumes/data/Documents/app-builder/pkg/download/downloader.go:220
github.com/develar/app-builder/pkg/download.(*Downloader).Download
        /Volumes/data/Documents/app-builder/pkg/download/downloader.go:114
github.com/develar/app-builder/pkg/electron.(*ElectronDownloader).doDownload
        /Volumes/data/Documents/app-builder/pkg/electron/electronDownloader.go:192
github.com/develar/app-builder/pkg/electron.(*ElectronDownloader).Download
        /Volumes/data/Documents/app-builder/pkg/electron/electronDownloader.go:177
github.com/develar/app-builder/pkg/electron.downloadElectron.func1.1
        /Volumes/data/Documents/app-builder/pkg/electron/electronDownloader.go:73
github.com/develar/app-builder/pkg/util.MapAsyncConcurrency.func2
        /Volumes/data/Documents/app-builder/pkg/util/async.go:68
runtime.goexit
        /usr/local/Cellar/go/1.14.2_1/libexec/src/runtime/asm_amd64.s:1373
  ⨯ F:\Electron\electron-vue-template\node_modules\app-builder-bin\win\x64\app-builder.exe exited with code ERR_ELECTRON_BUILDER_CANNOT_EXECUTE  stackTrace=
                                                                                                                                                   Error: F:\Electron\electron-vue-template\node_modules\app-builder-bin\win\x64\app-builder.exe exited with code ERR_ELECTRON_BUILDER_CANNOT_EXECUTE
                                                                                                                                                       at ChildProcess.<anonymous> (F:\Electron\electron-vue-template\node_modules\builder-util\src\util.ts:243:14)
                                                                                                                                                       at Object.onceWrapper (events.js:417:26)
                                                                                                                                                       at ChildProcess.emit (events.js:310:20)
                                                                                                                                                       at maybeClose (internal/child_process.js:1021:16)
                                                                                                                                                       at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by umbrella22** [comment]
@goodZhaoliu The wrong information indicates that you failed to download electron. If you are from mainland China, please check the Chinese document in readme. If you still have `Get xxx` in NSIS stage, you need to get the corresponding file from [here](https://gitee.com/Zh-Sky/HardToDownloadLib). If you come from other areas, you should configure the electron CDN mirror belonging to your current country.
