### ISSUE TITLE
使用npm install 后使用 npm run dev 时会报错，提示Electron 未正确安装。

### ISSUE THREAD

**Issue by ideacco** [umbrella22/electron-vue-template#2]
出现的问题：
使用npm install 后使用 npm run dev 时会报错，提示Electron 未正确安装。
期望：
使用 npm run dev 会正常运行项目

Electron : 6.0.11
Npm : 6.9.0
Node: v12.4.0
系统mac：10.14.6

```

kendemacbook:electron-vue-template ken$ npm run dev

> electron-vue-admin@0.0.1 dev /Users/ken/Documents/WORK/Sleepon Code/Electron-dataview/electron-vue-template
> node .electron-vue/dev-runner.js

/Users/ken/Documents/WORK/Sleepon Code/Electron-dataview/electron-vue-template/node_modules/electron/index.js:14
    throw new Error('Electron failed to install correctly, please delete node_modules/electron and try installing again')
    ^

Error: Electron failed to install correctly, please delete node_modules/electron and try installing again
    at getElectronPath (/Users/ken/Documents/WORK/Sleepon Code/Electron-dataview/electron-vue-template/node_modules/electron/index.js:14:11)
    at Object.<anonymous> (/Users/ken/Documents/WORK/Sleepon Code/Electron-dataview/electron-vue-template/node_modules/electron/index.js:18:18)
    at Module._compile (internal/modules/cjs/loader.js:774:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:785:10)
    at Module.load (internal/modules/cjs/loader.js:641:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Module.require (internal/modules/cjs/loader.js:681:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (/Users/ken/Documents/WORK/Sleepon Code/Electron-dataview/electron-vue-template/.electron-vue/dev-runner.js:4:18)
    at Module._compile (internal/modules/cjs/loader.js:774:30)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! electron-vue-admin@0.0.1 dev: `node .electron-vue/dev-runner.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the electron-vue-admin@0.0.1 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/ken/.npm/_logs/2019-10-02T17_25_57_495Z-debug.log

```
PS:
`已经尝试使用：` npm install 以及 yarn run dev 均会有以上提示。`
`在其他vue-electron项目中均未报此错误。`

**Comment by ideacco** [comment]
通过修改package.json 文件中electron的版本号修复了本问题。

**Comment by umbrella22** [comment]
@ideacco  = =其实这个错误是因为。。。之前你下载的electron没有完全下载下来你关闭了下载，导致electron安装失败，提示中式告知您需要删除node_modules文件夹，您之所以更改版本号获得成功是因为您计算机中已有对应版本包的electron包，而且在国内的复杂网络环境，我还是建议您按照我readme中的如何安装去设置electron的淘宝下载路径以获取最新的electron，还有就是打包过程由于我激进更新了版本，在您计算机中可能不会拥有最新的nsis打包环境，我还是建议您手动去下载对应依赖，这里我就不做太多阐述

**Comment by umbrella22** [comment]
emm，可能第一句描述不太详细，出现您这个问题的操作是，npm install后在安装electron位置等待时间过久导致您自己终止了安装，或者是直接超时导致安装进程进入下一步而直接跳过了electron的下载，在您npm run dev的时候，由于并没有下载对应版本的electron依赖包，就会出现您当前的报错信息。假期回复没有非常及时，这里表示歉意。
