### ISSUE TITLE
run dev throw error: install electron incorrectly

### ISSUE THREAD

**Issue by goodZhaoliu** [umbrella22/electron-vue-template#7]
Allways Throw Error Like：
>yarn dev
yarn run v1.21.1
$ node .electron-vue/dev-runner.js
F:\Electron\ZJICX\node_modules\electron\index.js:14
    throw new Error('Electron failed to install correctly, please delete node_modules/electron and try installing again')
    ^

Error: Electron failed to install correctly, please delete node_modules/electron and try installing again
    at getElectronPath (F:\Electron\ZJICX\node_modules\electron\index.js:14:11)
    at Object.<anonymous> (F:\Electron\ZJICX\node_modules\electron\index.js:18:18)
    at Module._compile (internal/modules/cjs/loader.js:1151:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1171:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Module.require (internal/modules/cjs/loader.js:1040:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (F:\Electron\ZJICX\.electron-vue\dev-runner.js:14:18)
    at Module._compile (internal/modules/cjs/loader.js:1151:30)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

My Electron Ver Is 7.1.11

**Comment by umbrella22** [comment]
> **throw new Error('Electron failed to install correctly, please delete node_modules/electron and try installing again')**


This error seems to be caused by your current network cannot download the electron correctly.
If you are not in a network in China, in fact, it is unlikely that the electron download fails. It is recommended that you delete the node_module folder and try a few times. **If you are in a network in China, please view the Chinese documentation**.

**Comment by goodZhaoliu** [comment]
请问您是中国人吗？有QQ交流群吗？

**Comment by goodZhaoliu** [comment]
当我把Electron改为5.0或6.0或6.1.8就可以了，谢谢了！

**Comment by umbrella22** [comment]
@goodZhaoliu 是啊我是中国人啊。。。qq群的话暂时没有建，你降低版本成功的原因是因为你的电脑上原本就有这些版本的缓存。。emm。。。我的readme中有一个中文在线文档，里面有关于安装部分的说明。
